version: "3.7"
services:
  webserver:
    build: .
    image: puckel/docker-airflow:latest
    container_name: webserver_container
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - 8080:8080
    networks:
      - backend
    restart: always
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: airflow
    container_name: mysql_container
    ports:
      - 3306:3306
    networks:
      - backend
networks:
  backend:
    driver: "bridge"